/* DATA MEMORY
 *  Functionality/Behavior:
 *  ->  contains 4 SRAM Macros generated by OpenRAM. 
 *  ->  word size is 32 bits, 256 entries per macro with 1 read-write port
 *  ->  module acts as bridge between chip and SRAMs
 *  ->  for scalar ops, LSB 2 bits determine bank address, rest of the bits determine address 
        inside the bank. 
 *  ->  vector ops read and write to all 4 banks simultaneously, vc[0]-> bank0, vc[1]-> bank1 
        and so on
 *  Inputs:
 *  ->  clock
 *  ->  read enable and write enable
 *  ->  read/write address
 *  ->  data in
 *  Outputs:
 *  ->  data out
 *  ->  valid (read is valid only if valid is 1)
 *  Notes:
 *  ->  for scalar ops, 
 *  ->  chips are always active (idea is reduces comb logic, add gating if hurts timing)
 *  ->  the address input of SRAM has one additional bit, padding address with one 0 for that
 *  ->  din and dout of sram is 33 bits, pad with 0 to prevent issues
 *  ->  spare wen will always be 0. Added that column due to OpenRAM quirk
 *  Potential Future Optimizations:
 *  ->  Support simultaneous read and write of upto 4 scalar values
 *  ->  lsb 2 bits for vector address inputs are ignored, the values are hard coded in this module
 *  ->  chip select and write enable inputs for the sram modules are active low
 *  ->  both read enable and write enable inputs present to prevent propogation of dont cares from
        SRAMs when there is no read or write
 *  ->  if both read enable and write enable inputs are 1 (illegal case), we do a read
 */

module dmem (
    input  logic clk_i,
    input  packet_pkg::dmem_request_t dmem_request_i,
    /*  logic [3:0]   write_enable;
        logic [7:0]   address;
        logic [127:0] data;
    */
    
    output signal_pkg::vector_data_t data_o
);
    
    logic[32:0] read[3:0];
    logic[3:0]  write_enable;
    
    sky130_sram_1kbyte_1rw_32x256_32 u_dmem3(
        .clk0(clk_i),
        .csb0(1'b0),
        .web0(write_enable[3]),
        .spare_wen0(1'b0),
        .addr0({1'b0, dmem_request_i.address}),
        .din0({1'b0, dmem_request_i.data[127:96]}),
        .dout0(read[3])
    );

    sky130_sram_1kbyte_1rw_32x256_32 u_dmem2(
        .clk0(clk_i),
        .csb0(1'b0),
        .web0(write_enable[2]),
        .spare_wen0(1'b0),
        .addr0({1'b0, dmem_request_i.address}),
        .din0({1'b0, dmem_request_i.data[95:64]}),
        .dout0(read[2])
    );

    sky130_sram_1kbyte_1rw_32x256_32 u_dmem1(
        .clk0(clk_i),
        .csb0(1'b0),
        .web0(write_enable[1]),
        .spare_wen0(1'b0),
        .addr0({1'b0, dmem_request_i.address}),
        .din0({1'b0, dmem_request_i.data[63:32]}),
        .dout0(read[1])
    );

    sky130_sram_1kbyte_1rw_32x256_32 u_dmem0(
        .clk0(clk_i),
        .csb0(1'b0),
        .web0(write_enable[0]),
        .spare_wen0(1'b0),
        .addr0({1'b0, dmem_request_i.address}),
        .din0({1'b0, dmem_request_i.data[31:0]}),
        .dout0(read[0])
    );

    genvar i;
    generate
        for(i=0; i<4; i++) begin : gen_bank_compile
            assign write_enable[i] = ~dmem_request_i.write_enable[i];
            assign data_o[i] = read[i][31:0];
        end
    endgenerate

endmodule