/* INSTRUCTION MEMORY
 *  Functionality/Behavior:
 *  ->  contains single SRAM Macro generated by OpenRAM. (common macro for both)
 *  ->  word size is 32 bits, 256 entries with 1 read-write port
 *  ->  module acts as bridge between chip and IMEM SRAM
 *  ->  Also supports pre-loading of instructions.
 *  ->  read goes to fetch module and write comes from the external input 
 *  Inputs:
 *  ->  clock
 *  ->  read enable from fetch
 *  ->  write enable from external source for preloading instructions
 *  ->  read address from fetch
 *  ->  read address from external souce
 *  ->  data in from external source
 *  Outputs:
 *  ->  data out (irrespective of whether read is enabled or not, it is propogated)
 *  ->  output valids to fetch
 *  Notes:
 *  ->  chips are always active (idea is reduces comb logic, add gating if hurts timing)
 *  ->  chip select and write enable inputs for the sram modules are active low
 *  ->  both read enable and write enable inputs present to prevent propogation of dont cares from
        SRAMs when there is no read or write
 *  ->  if both read enable and write enable inputs are 1 (illegal case), we do a write
 *  ->  Reset does not propogate to IMEM, Macros power up to X. 
 */

module imem (
    input  logic clk_i,
    input  packet_pkg::imem_request_t imem_request_i,

    output logic[31:0] data_o
);
    logic[32:0] read;

    sky130_sram_1kbyte_1rw_32x256_32 u_imem(
        .clk0(clk_i),
        .csb0(1'b0),
        .web0(~imem_request_i.write_enable),
        .spare_wen0(1'b0),
        .addr0({1'b0, imem_request_i.address}),
        .din0({1'b0, imem_request_i.data}),
        .dout0(read)
    );

    assign data_o = read[31:0];

endmodule