/* ------------------------------------------------------------------------------------------------
 *                                           CORE MODULE
 * ------------------------------------------------------------------------------------------------
 *
 *  Functions/Behavior
 *  ->  Top-level integration module that wires together all pipeline stages
 *  ->	Scalar and vector instructions share the same in-order front end but are dispatched to 
        separate reservation stations and physical register files.
 *  ->	Supports pre-loading of both the scalar and vector Physical Register Files (PRFs). Preload
        inputs take priority over writeback bus.
 *  ->	Generates a global flush signal (driven by the ROB on branch misprediction) that propagates
        to every pipeline stage simultaneously.
 *  ->	Computes per-FU ready signals by ANDing the EX-stage ready and WB-stage ready. 

 *
 *  Inputs:
 *  ->	clk & reset_n
 *  ->	compute_i — Enables instruction fetch. When deasserted, the fetch unit stalls and no new
        instructions enter the pipeline.
 *  ->	sc_prf_preload_en_i — When high, bypasses writeback and writes sc_prf_preload_data_i into
        the scalar PRF at the address given by sc_prf_preload_addr_i.
 *  ->	sc_prf_preload_data_i — Scalar preload write data (32-bit scalar value).
 *  ->	sc_prf_preload_addr_i — Scalar PRF address to write during preload.
 *  ->	vc_prf_preload_en_i — Same as scalar preload enable but for the vector PRF.
 *  ->	vc_prf_preload_data_i — Vector preload write data (128-bit vector value).
 *  ->	vc_prf_preload_addr_i — Vector PRF address to write during preload.
 *  ->	imem_dout_i — 32-bit instruction word returned from instruction memory.
 *  ->	imem_addr_i — Current instruction memory address (provided externally; driven into the
        fetch unit for PC tracking).
 *  ->	dmem_dout_i — 128-bit data word returned from data memory (both scalar and vector loads).
 *
 *  Outputs:
 *  ->	imem_request_o — Instruction memory request packet generated by the fetch unit; contains
        the PC of next instruction to fetch.
 *  ->	dmem_request_o — Data memory request packet generated by the DMEM controller; contains 
        address, data, and control signals for scalar and vector loads/stores.
 *
 *  Notes:
 *  ->	FU index mapping —  Scalar: 0 = ALU0, 1 = ALU1, 2 = MUL/DIV, 3 = LSU. 
                            Vector: 0 = VALU, 1 = VLSU. 
    ->  Above used as array indices throughout the module.
 *  ->  The multiply-divide unit additionally requires that no read request or execute request is
        currently in-flight before asserting ready to the RS. (Quirk due to multi-cycle execution)
 *  ->	Scalar and vector load store instructions are fed into a single ex_load_store unit. The
        scalar and vector store data arrive on separate signals. Both ready signals must be true 
        before a new memory instruction is dispatched.
 *  ->	The ECALL instruction is used as the program termination signal.
 *  ->	Fetch is the current I/O boundary
 *  ->	Flush is driven directly from the ROB output with no additional register stage. All 
        submodules must tolerate a same-cycle flush.
 *
 * ------------------------------------------------------------------------------------------------
 */

// import statements for OpenROAD, already included in EDA playground
//import config_pkg::*;

module core #()(
    input  logic clk_i,
    input  logic reset_ni,

    input  logic compute_i,

    input  logic sc_prf_preload_en_i,
    input  signal_pkg::data_t sc_prf_preload_data_i,
    input  signal_pkg::prf_tag_t sc_prf_preload_addr_i, 

    input  logic vc_prf_preload_en_i,
    input  signal_pkg::vector_data_t vc_prf_preload_data_i,
    input  signal_pkg::prf_tag_t vc_prf_preload_addr_i, 

    input  signal_pkg::data_t imem_dout_i,
    input  logic [7:0] imem_addr_i,
    output packet_pkg::imem_request_t imem_request_o,

    input  logic [127:0] dmem_dout_i,
    output packet_pkg::dmem_request_t dmem_request_o

);

    // broadcast signals
    logic flush;

    // fetch output signals
    signal_pkg::data_t fetched_instr;
    signal_pkg::pc_t   fetched_pc;
    logic fetch_valid;

    // decode output signals
    packet_pkg::decoded_instr_t decoded_instr;

    // dispatched instruction signals
    packet_pkg::decoded_instr_t dispatched_instr;
    signal_pkg::rs_slot_id_t dispatched_instr_rs_slot_id;
    logic queue_ready, decode_ready, decoded_instr_en;

    // signals from RS to Queue with freed RS Slot IDs
    signal_pkg::rs_slot_id_t released_rs_slot_id_arr [RS_DISPATCH_COUNT-1:0];
    logic rs_slot_released_arr[RS_DISPATCH_COUNT-1:0];

    logic rob_full, arr_full;

    // signals from reservation stations to prf 
    packet_pkg::read_request_t sc_rd_req[SCALAR_EX_COUNT-1:0];
    packet_pkg::read_request_t br_rd_req;
    packet_pkg::read_request_t vc_alu_rd_req;
    
    packet_pkg::vc_lsu_read_request_t vc_lsu_rd_req;
    signal_pkg::prf_tag_t vc_alu_rd_req_tag;
    
    // PRF -> EX signals
    packet_pkg::sc_ex_request_t sc_ex_req[SCALAR_EX_COUNT-1:0];
    packet_pkg::sc_ex_request_t br_ex_req;
    packet_pkg::vc_alu_ex_request_t vc_alu_ex_req;
    packet_pkg::vc_lsu_ex_request_t vc_lsu_ex_req;

    signal_pkg::data_t sc_ls_store_data;
    signal_pkg::data_t vc_alu_sc_operand; 
    signal_pkg::vector_data_t vc_ls_store_data;

    // functional units output signals
    // EX -> WB
    
    packet_pkg::sc_ex_result_t sc_ex_result[SCALAR_EX_COUNT-1:0];
    packet_pkg::br_result_t br_ex_result;
    packet_pkg::vc_ex_result_t vc_ex_result[VECTOR_EX_COUNT-1:0];
    packet_pkg::sc_ex_result_t sc_lsu_result;
    packet_pkg::vc_ex_result_t vc_lsu_result;

    packet_pkg::load_store_entry_t lsu_output;
    packet_pkg::store_retire_request_t store_retire_req;

    // ready signals from FUs
    // SCALAR: EX -> RS
    // VECTOR: EX -> PRF

    logic sc_ex_ready[SCALAR_EX_COUNT-1:0];
    logic br_ex_ready;
    logic vc_ex_ready[VECTOR_EX_COUNT-1:0];
    logic lsu_ready;

    // ready signals from WB
    // WB -> RS
    logic sc_wb_ready[SCALAR_EX_COUNT-1:0];
    logic vc_wb_ready[VECTOR_EX_COUNT-1:0];

    // ready inputs into RS, bitwise and of sc_ex_ready and sc_wb_ready
    logic sc_rs_ex_ready[SCALAR_EX_COUNT-1:0];
    logic vc_rs_ex_ready[VECTOR_EX_COUNT-1:0];

    /*  Naming Convention
        Fetched OP -> fetched_instr
        Decoded OP -> decoded_instr
        Queue OP   -> dispatched_instr
        ARR op     -> alloc_instr
        PRF op to RS -> rs_request
        RS to EX   -> ex_request
        RS to PRF  -> vc_read_request
        PRF to EX  -> ex_request
        ex to wb   -> ex_result
        ROB retire -> retire_instr
    */
    
// ------------------------------------------------------------------------------------------------
//                                           ALL INTERFACES
// ------------------------------------------------------------------------------------------------

    if_alloc_bus u_alloc_bus();

    if_data_bus #(.T(signal_pkg::data_t)) u_sc_data_bus();
    if_data_bus #(.T(signal_pkg::vector_data_t)) u_vc_data_bus();
    
    if_retirement_bus u_retirement_bus();

    if_data_bus #(.T(signal_pkg::data_t)) u_sc_prf_input();
    if_data_bus #(.T(signal_pkg::vector_data_t)) u_vc_prf_input();

    genvar i;

    always_comb begin
        sc_rs_ex_ready[0] = sc_ex_ready[0] && sc_wb_ready[0];
        sc_rs_ex_ready[1] = sc_ex_ready[1] && sc_wb_ready[1];
        sc_rs_ex_ready[2] = sc_ex_ready[2] && sc_wb_ready[2] && !(sc_rd_req[2].valid) && !(sc_ex_req[2].valid);
        sc_rs_ex_ready[3] = sc_ex_ready[3] && sc_wb_ready[3];

        vc_rs_ex_ready[0] = vc_ex_ready[0] && vc_wb_ready[0];
        vc_rs_ex_ready[1] = vc_ex_ready[1] && vc_wb_ready[1];
    end

    assign lsu_ready = sc_rs_ex_ready[3] && vc_rs_ex_ready[1];

    always_comb begin
        /*
         * Handling pre-loading of PRF
         */

        if (sc_prf_preload_en_i) begin
            u_sc_prf_input.valid   =  sc_prf_preload_en_i;
            u_sc_prf_input.prf_tag =  sc_prf_preload_addr_i;
            u_sc_prf_input.data    =  sc_prf_preload_data_i;
        end
        else begin
            u_sc_prf_input.valid   = u_sc_data_bus.valid;
            u_sc_prf_input.prf_tag = u_sc_data_bus.prf_tag;
            u_sc_prf_input.data    = u_sc_data_bus.data;
        end

        if (vc_prf_preload_en_i) begin
            u_vc_prf_input.valid   = vc_prf_preload_en_i;
            u_vc_prf_input.prf_tag = vc_prf_preload_addr_i;
            u_vc_prf_input.data    = vc_prf_preload_data_i;
        end
        else begin
            u_vc_prf_input.valid = u_vc_data_bus.valid;
            u_vc_prf_input.prf_tag = u_vc_data_bus.prf_tag;
            u_vc_prf_input.data = u_vc_data_bus.data;
        end 

    end

// ------------------------------------------------------------------------------------------------
//                                        IN ORDER FRONT END
// ------------------------------------------------------------------------------------------------

    fe_fetch u_fetch (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .compute_i(compute_i),
        .ready_i(decode_ready),
        .retire_instr_i(u_retirement_bus),
        .fetched_instr_o(fetched_instr),
        .fetched_pc_o(fetched_pc),
        .fetch_valid_o(fetch_valid),
        .imem_instr_i(imem_dout_i),
        .imem_addr_i(imem_addr_i),
        .imem_req_o(imem_request_o)
    );

    fe_decode u_decode (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .fetched_instr_i(fetched_instr),
        .fetched_pc_i(fetched_pc),
        .fetch_valid_i(fetch_valid),
        .decode_ready_o(decode_ready),
        .queue_ready_i(queue_ready),
        .decoded_instr_o(decoded_instr),
        .decoded_instr_en_o(decoded_instr_en)
    );

    fe_instruction_queue u_instr_q (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .decoded_instr_i(decoded_instr),
        .decoded_instr_en_i(decoded_instr_en),
        .released_rs_slot_id_i(released_rs_slot_id_arr),
        .rs_slot_released_i(rs_slot_released_arr),
        .rob_full_i(rob_full),
        .arr_full_i(arr_full),
        .dispatched_instr_o(dispatched_instr),
        .rs_slot_id_o(dispatched_instr_rs_slot_id),
        .queue_ready_o(queue_ready)
    );

// ------------------------------------------------------------------------------------------------
//                                 INSTRUCTION STATE MANAGEMENT
// ------------------------------------------------------------------------------------------------

    ooo_arr_unit u_alloc_rename_retire (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .dispatched_instr_i(dispatched_instr),
        .rs_slot_id_i(dispatched_instr_rs_slot_id),
        .retire_instr_i(u_retirement_bus),
        .sc_wb_instr_i(u_sc_data_bus),
        .vc_wb_instr_i(u_vc_data_bus),
        .alloc_instr_o(u_alloc_bus),
        .arr_full_o(arr_full)
    );

    ooo_reorder_buffer u_reorder_buffer (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .alloc_instr_io(u_alloc_bus),
        .sc_data_bus_i(u_sc_data_bus),
        .vc_data_bus_i(u_vc_data_bus),
        .branch_result_i(br_ex_result),
        .store_retire_req_i(store_retire_req),
        .retire_instr_o(u_retirement_bus),
        .rob_full_o(rob_full),
        .flush_o(flush)
    );

// ------------------------------------------------------------------------------------------------
//                                           SCHEDULING
// ------------------------------------------------------------------------------------------------

    rs_scalar_2issue #(.CHIP_SELECT(signal_pkg::CS_SALU)) u_scalar_alu_rs (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .rs_request_i(u_alloc_bus),
        .sc_data_bus_i(u_sc_data_bus),
        .sc_ex0_ready_i(sc_rs_ex_ready[0]),
        .sc_ex1_ready_i(sc_rs_ex_ready[1]),
        .sc_rd_req0_o(sc_rd_req[0]),
        .sc_rd_req1_o(sc_rd_req[1]),
        .released_rs_slot_id_o(released_rs_slot_id_arr[1:0]),
        .rs_slot_released_o(rs_slot_released_arr[1:0])
    );

    rs_scalar_1issue #(.CHIP_SELECT(signal_pkg::CS_MULDIV)) u_scalar_muldiv_rs (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .rs_request_i(u_alloc_bus),
        .sc_data_bus_i(u_sc_data_bus),
        .sc_ex_ready_i(sc_rs_ex_ready[2]),
        .sc_rd_req_o(sc_rd_req[2]),
        .released_rs_slot_id_o(released_rs_slot_id_arr[2]),
        .rs_slot_released_o(rs_slot_released_arr[2])
    );

    rs_load_store u_lsu_rs (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .rs_request_i(u_alloc_bus),
        .sc_data_bus_i(u_sc_data_bus),
        .vc_data_bus_i(u_vc_data_bus),
        .ls_read_request_o(sc_rd_req[3]),
        .vc_lsu_rd_req_o(vc_lsu_rd_req),
        .lsu_ready_i(lsu_ready),
        .released_rs_slot_id_o(released_rs_slot_id_arr[3]),
        .rs_slot_released_o(rs_slot_released_arr[3])
    );

    rs_scalar_1issue #(.CHIP_SELECT(signal_pkg::CS_BRANCH)) u_branch_rs (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .rs_request_i(u_alloc_bus),
        .sc_data_bus_i(u_sc_data_bus),
        .sc_ex_ready_i(br_ex_ready),
        .sc_rd_req_o(br_rd_req),
        .released_rs_slot_id_o(released_rs_slot_id_arr[4]),
        .rs_slot_released_o(rs_slot_released_arr[4])
    );

    rs_vector_1issue #(.CHIP_SELECT(signal_pkg::CS_VALU)) u_vector_alu_rs (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .rs_request_i(u_alloc_bus),
        .sc_data_bus_i(u_sc_data_bus),
        .vc_data_bus_i(u_vc_data_bus),
        .vc_ex_ready_i(vc_rs_ex_ready[0]),
        .vc_read_request_o(vc_alu_rd_req),
        .sc_read_request_tag_o(vc_alu_rd_req_tag),
        .released_rs_slot_id_o(released_rs_slot_id_arr[5]),
        .rs_slot_released_o(rs_slot_released_arr[5])
        
    );

// ------------------------------------------------------------------------------------------------
//                                              DATA
// ------------------------------------------------------------------------------------------------

    data_dmem_controller u_dmem_controller (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .lsu_output(lsu_output),
        .dmem_dout_i(dmem_dout_i),
        .dmem_req_o(dmem_request_o),
        .sc_wb_o(sc_ex_result[3]),
        .vc_wb_o(vc_ex_result[1])
    );
    
    data_sc_regfile_3sc u_scalar_prf_replica0 (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .precalc_i(u_alloc_bus),
        .sc_wb_instr_i(u_sc_prf_input),
        .sc_rd_req0_i(sc_rd_req[0]),
        .sc_ex_req0_o(sc_ex_req[0]),
        .sc_rd_req1_i(sc_rd_req[1]),
        .sc_ex_req1_o(sc_ex_req[1]),
        .sc_rd_req2_i(sc_rd_req[2]),
        .sc_ex_req2_o(sc_ex_req[2])
    ); 

    data_sc_regfile_br_valu_ls u_scalar_prf_replica1 (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .precalc_i(u_alloc_bus),
        .sc_wb_instr_i(u_sc_prf_input),
        .sc_br_rd_req_i(br_rd_req),
        .sc_br_ex_req_o(br_ex_req),
        .vc_alu_rd_req_tag_i(vc_alu_rd_req_tag),
        .vc_alu_sc_operand_o(vc_alu_sc_operand),
        .ls_rd_req_i(sc_rd_req[3]),
        .ls_ex_req_o(sc_ex_req[3]),
        .ls_store_data_o(sc_ls_store_data)
    );  

    data_vc_regfile_valu_ls u_vector_prf (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .vc_wb_instr_i(u_vc_prf_input),
        .vc_alu_rd_req_i(vc_alu_rd_req),
        .vc_alu_ex_req_o(vc_alu_ex_req),
        .vc_lsu_rd_req_i(vc_lsu_rd_req),
        .vc_lsu_ex_req_o(vc_lsu_ex_req)
    ); 

// ------------------------------------------------------------------------------------------------
//                                          FUNCTIONAL UNITS
// ------------------------------------------------------------------------------------------------

    ex_scalar_alu u_scalar_alu0 (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .sc_ex_request_i(sc_ex_req[0]),
        .sc_ex_result_o(sc_ex_result[0]),
        .sc_ex_ready_o(sc_ex_ready[0])
    );

    ex_scalar_alu u_scalar_alu1 (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .sc_ex_request_i(sc_ex_req[1]),
        .sc_ex_result_o(sc_ex_result[1]),
        .sc_ex_ready_o(sc_ex_ready[1])
    );

    ex_scalar_muldiv u_scalar_muldiv(
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .sc_ex_request_i(sc_ex_req[2]),
        .sc_ex_result_o(sc_ex_result[2]),
        .sc_ex_ready_o(sc_ex_ready[2])
    ); 

    ex_branch u_branch (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .br_ex_request_i(br_ex_req),
        .br_ex_result_o(br_ex_result),
        .br_ex_ready_o(br_ex_ready)
    );

    ex_load_store u_lsu (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .lsu_request_i(sc_ex_req[3]),
        .sc_store_data_i(sc_ls_store_data),
        .vc_lsu_ex_request_i(vc_lsu_ex_req),
        .retire_instr_i(u_retirement_bus),
        .lsu_output_o(lsu_output),
        .sc_fwd_load_o(sc_lsu_result),
        .vc_fwd_load_o(vc_lsu_result),
        .store_retire_req_o(store_retire_req),
        .sc_ex_ready_o(sc_ex_ready[3]),
        .vc_ex_ready_o(vc_ex_ready[1])
    );

    ex_vector_alu u_vector_alu (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .vc_ex_request_i(vc_alu_ex_req),
        .sc_operand_i(vc_alu_sc_operand),
        .vc_ex_result_o(vc_ex_result[0]),
        .vc_ex_ready_o(vc_ex_ready[0])
    );


// ------------------------------------------------------------------------------------------------
//                                                WRITEBACK
// ------------------------------------------------------------------------------------------------

    wb_scalar u_scalar_writeback (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .ex_result_i(sc_ex_result),
        .lsu_result_i(sc_lsu_result),
        .wb_ready_o(sc_wb_ready),
        .data_bus_o(u_sc_data_bus)
    );

    wb_vector u_vector_writeback (
        .clk_i(clk_i),
        .reset_ni(reset_ni),
        .flush_i(flush),
        .ex_result_i(vc_ex_result),
        .lsu_result_i(vc_lsu_result),
        .wb_ready_o(vc_wb_ready),
        .data_bus_o(u_vc_data_bus)
    );

endmodule